import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '@/components/ui/button';
import { colors, radii, spacing } from '@/constants/design';
import { INSTRUMENT_OPTIONS } from '@/constants/instruments';
import { saveInstrumentMaterial } from '@/features/organizations/organization-service';
import { toast } from '@/store/toast-store';

export default function MaterialEditorScreen() {
  const { organizationId = '', songId = '', songTitle = 'Canción' } = useLocalSearchParams<{ organizationId: string; songId: string; songTitle?: string }>(); const [instrument, setInstrument] = useState<(typeof INSTRUMENT_OPTIONS)[number]>(INSTRUMENT_OPTIONS[0]); const [key, setKey] = useState(''); const [content, setContent] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async () => { if (!instrument) return; setSaving(true); const error = await saveInstrumentMaterial({ organizationId, songId, instrumentName: instrument.name, key: key || instrument.transpositionKey, ...(content ? { contentRaw: content } : {}), ...(notes ? { notes } : {}) }); setSaving(false); if (error) { toast.error(error); return; } toast.success('Material de instrumento guardado.'); router.back(); };
  return <SafeAreaView style={styles.safe}><View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.cancel}>Cancelar</Text></Pressable><Text style={styles.navTitle}>Material</Text><Button compact label={saving ? 'Guardando…' : 'Guardar'} disabled={saving} onPress={submit} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>MATERIAL POR INSTRUMENTO</Text><Text style={styles.title}>{songTitle}</Text><Text style={styles.label}>INSTRUMENTO</Text><View style={styles.options}>{INSTRUMENT_OPTIONS.map((option) => <Pressable key={option.name} onPress={() => { setInstrument(option); if (!key) setKey(option.transpositionKey); }} style={[styles.option, instrument.name === option.name && styles.optionActive]}><Text style={styles.optionText}>{option.name}</Text><Text style={styles.optionKey}>{option.transpositionKey}</Text></Pressable>)}</View><Text style={styles.label}>TONALIDAD / TRANSPOSICIÓN</Text><TextInput value={key} onChangeText={setKey} placeholder={instrument.transpositionKey} placeholderTextColor="#77706C" style={styles.input} /><Text style={styles.label}>CONTENIDO ESPECÍFICO</Text><TextInput multiline value={content} onChangeText={setContent} placeholder="Partitura textual, secuencia de notas o indicaciones" placeholderTextColor="#77706C" style={[styles.input, styles.contentInput]} /><Text style={styles.label}>NOTAS</Text><TextInput multiline value={notes} onChangeText={setNotes} placeholder="Notas para este instrumento" placeholderTextColor="#77706C" style={[styles.input, styles.notesInput]} /></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, nav: { height: 64, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, cancel: { color: colors.textSecondary, fontSize: 13 }, navTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, content: { padding: spacing.lg, paddingBottom: 80, width: '100%', maxWidth: 650, alignSelf: 'center' }, eyebrow: { color: colors.accent, fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontFamily: 'serif', fontSize: 29, fontWeight: '600', marginTop: 8 }, label: { color: colors.textSecondary, fontSize: 9, fontWeight: '900', letterSpacing: 1.3, marginTop: 20, marginBottom: 8 }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, option: { flexDirection: 'row', gap: 7, paddingHorizontal: 10, paddingVertical: 8, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border }, optionActive: { borderColor: colors.accent, backgroundColor: '#281A1D' }, optionText: { color: colors.text, fontSize: 10 }, optionKey: { color: colors.accent, fontSize: 9, fontWeight: '800' }, input: { minHeight: 50, paddingHorizontal: 14, color: colors.text, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md }, contentInput: { minHeight: 190, paddingTop: 14, textAlignVertical: 'top', fontFamily: 'monospace' }, notesInput: { minHeight: 90, paddingTop: 14, textAlignVertical: 'top' } });
