import { useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { SongRow } from '@/components/song-row';
import { colors, radii, spacing } from '@/constants/design';
import { listInstrumentMaterials, listOrganizationMembers, listOrganizationSetlists, listOrganizationSongs } from '@/features/organizations/organization-service';
import { useAuthStore } from '@/store/auth-store';
import { useSetlistStore } from '@/store/setlist-store';
import { useSongStore } from '@/store/song-store';

export default function SetlistDetailScreen() {
  const { id = '', organizationId } = useLocalSearchParams<{ id: string; organizationId?: string }>(); const user = useAuthStore((state) => state.user);
  const localSetlist = useSetlistStore((state) => state.setlists.find((item) => item.id === id)); const localSongs = useSongStore((state) => state.songs);
  const { data: remoteSetlists = [] } = useQuery({ queryKey: ['organization-setlists', organizationId], queryFn: () => listOrganizationSetlists(organizationId!), enabled: Boolean(organizationId) });
  const { data: remoteSongs = [] } = useQuery({ queryKey: ['organization-songs', organizationId], queryFn: () => listOrganizationSongs(organizationId!), enabled: Boolean(organizationId) });
  const { data: members = [] } = useQuery({ queryKey: ['organization-members', organizationId], queryFn: () => listOrganizationMembers(organizationId!), enabled: Boolean(organizationId) });
  const mergeSongs = useSongStore((state) => state.mergeRemoteSongs); useEffect(() => { if (remoteSongs.length) mergeSongs(remoteSongs); }, [mergeSongs, remoteSongs]);
  const setlist = localSetlist ?? remoteSetlists.find((item) => item.id === id); const songs = organizationId ? remoteSongs : localSongs; const orderedSongs = (setlist?.songIds ?? []).map((songId) => songs.find((song) => song.id === songId)).filter(Boolean); const membership = members.find((member) => member.userId === user?.id); const primaryInstrument = membership?.instruments.find((instrument) => instrument.isPrimary) ?? membership?.instruments[0];
  const { data: materials = [] } = useQuery({ queryKey: ['instrument-materials', primaryInstrument?.instrumentId, remoteSongs.map((song) => song.remoteId).join(',')], queryFn: () => listInstrumentMaterials(remoteSongs.flatMap((song) => song.remoteId ? [song.remoteId] : []), primaryInstrument?.instrumentId), enabled: Boolean(organizationId && primaryInstrument && remoteSongs.length) });
  return <SafeAreaView style={styles.safe}><View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.navTitle}>PROGRAMA</Text><View style={{ width: 30 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>{setlist?.serviceDate ?? 'SIN FECHA'}</Text><Text style={styles.title}>{setlist?.title ?? 'Programa'}</Text>{setlist?.notes ? <View style={styles.notes}><Text style={styles.notesLabel}>NOTAS GENERALES</Text><Text style={styles.notesText}>{setlist.notes}</Text></View> : null}{organizationId ? <View style={styles.instrumentView}><Text style={styles.instrumentLabel}>TU VISTA</Text><Text style={styles.instrumentName}>{primaryInstrument?.instrumentName ?? 'Canción base'}</Text><Text style={styles.instrumentCopy}>{primaryInstrument ? `Se muestra material para ${primaryInstrument.instrumentName}; si no existe, verás la canción base.` : 'No tienes instrumento asignado en esta iglesia.'}</Text></View> : null}<Text style={styles.section}>{orderedSongs.length} CANCIONES</Text><View style={styles.list}>{orderedSongs.map((song, index) => { if (!song) return null; const material = materials.find((item) => item.songId === song.id); return <View key={song.id}><SongRow song={song} index={index + 1} />{material ? <View style={styles.material}><Text style={styles.materialLabel}>{material.instrumentName.toUpperCase()} · {material.key ?? song.key}</Text>{material.contentRaw ? <Text style={styles.materialContent}>{material.contentRaw}</Text> : null}{material.notes ? <Text style={styles.materialNotes}>{material.notes}</Text> : null}</View> : organizationId && primaryInstrument ? <Text style={styles.baseFallback}>Sin material específico · se usará la canción base</Text> : null}</View>; })}</View>{!orderedSongs.length ? <Text style={styles.empty}>Este programa no contiene canciones disponibles.</Text> : null}</ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, nav: { height: 58, paddingHorizontal: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, back: { color: colors.text, fontSize: 34 }, navTitle: { color: colors.textSecondary, fontSize: 9, fontWeight: '900', letterSpacing: 1.5 }, content: { padding: spacing.lg, paddingBottom: 100, width: '100%', maxWidth: 720, alignSelf: 'center' }, eyebrow: { color: colors.accent, fontSize: 9, fontWeight: '900', letterSpacing: 1.4 }, title: { color: colors.text, fontFamily: 'serif', fontSize: 34, fontWeight: '600', marginTop: 8 }, notes: { marginTop: 20, padding: 15, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, notesLabel: { color: colors.textSecondary, fontSize: 8, fontWeight: '900', letterSpacing: 1.2 }, notesText: { color: colors.text, fontSize: 12, lineHeight: 18, marginTop: 7 }, instrumentView: { marginTop: 14, padding: 15, borderRadius: radii.md, backgroundColor: '#1D1819', borderWidth: 1, borderColor: '#362326' }, instrumentLabel: { color: colors.accent, fontSize: 8, fontWeight: '900', letterSpacing: 1.2 }, instrumentName: { color: colors.text, fontSize: 15, fontWeight: '700', marginTop: 6 }, instrumentCopy: { color: colors.textSecondary, fontSize: 10, lineHeight: 15, marginTop: 4 }, section: { color: colors.textSecondary, fontSize: 9, fontWeight: '900', letterSpacing: 1.4, marginTop: 26, marginBottom: 10 }, list: { backgroundColor: colors.surface, borderRadius: radii.md, paddingHorizontal: 16, borderWidth: 1, borderColor: colors.border }, material: { marginBottom: 12, marginLeft: 46, padding: 11, borderRadius: radii.sm, backgroundColor: '#1D1819', borderLeftWidth: 2, borderLeftColor: colors.accent }, materialLabel: { color: colors.accent, fontSize: 8, fontWeight: '900' }, materialContent: { color: colors.text, fontFamily: 'monospace', fontSize: 11, lineHeight: 17, marginTop: 6 }, materialNotes: { color: colors.textSecondary, fontSize: 10, fontStyle: 'italic', marginTop: 5 }, baseFallback: { color: '#77706C', fontSize: 8, marginLeft: 46, marginBottom: 10 }, empty: { color: colors.textSecondary, textAlign: 'center', padding: 28 } });
